### ISSUE TITLE
Paraview crashes after importing converted .vtu/.vtk files from .f3grid (FLAC3D)

### ISSUE THREAD

**Issue by kuateric** [nschloe/meshio#509]
I converted a .f3grid file from FLAC3D to .vtu and .vtk. After important the file to Paraview to visualise the mesh, Paraview crashes and closes. Now I don't know if the problem is in the converted files or it is a issue with Paraview. 
Thank you

**Comment by nschloe** [comment]
@keurfonluu Best append the meshes here. (I think GitHub wants you to zip them first though.)

**Comment by kuateric** [comment]
@nschloe @keurfonluu here the mesh files: 
[testmodell3.zip](https://github.com/nschloe/meshio/files/3841653/testmodell3.zip)
Thank you for your help

**Comment by tianyikillua** [comment]
The problem is with FLAC3D itself (either the mesh file, or reading this file).

Using https://github.com/tianyikillua/paraview-meshio-reader to read the original FLAC3D file, ParaView also crashes.

```
<meshio mesh object>
  Number of points: 68796
  Number of elements:
    wedge: 38
    hexahedron: 61142
  Cell data: flac3d:zone
```
So we only have (read) 68796 points, however
```
np.any(mesh.cells["hexahedron"] >= mesh.points.shape[0], axis=1).sum() = 1253
```
so we have 1253 hexahedron elements that refer to non-existing nodes!

**Comment by nschloe** [comment]
Perhaps that's something we should assert against when writing a file.

**Comment by kuateric** [comment]
Thank you @tianyikillua for your remark. I will check the file and try again. It looks like i found my problem. I will let you know soon.

**Comment by nschloe** [comment]
Alright, there now is `meshio-info` which prints some details and issues if it found some.
```
meshio-info /tmp/testmodell3.f3grid 
```
```
<meshio mesh object>
  Number of points: 68796
  Number of elements:
    wedge: 38
    hexahedron: 61142
  Cell data: flac3d:zone

ATTENTION: Inconsistent mesh. Cells refer to nonexistent points.
```
Let's call this fixed.

**Comment by tianyikillua** [comment]
> Let's call this fixed.

Not necessarily.

Like Abaqus / Nastran, each cell is defined using the unique but not **necessarily naturally ordered** id's of the nodes.

In this case, the last node is referred to with the id 69773, even though it is the 68796th and the last point of the mesh.

![](https://user-images.githubusercontent.com/4027283/68779223-9240ae80-0634-11ea-8b6d-416f9e3771bf.png)

Currently it seems to me that `_flac3d.py` assumes that these id's correspond to the natural ordering of nodes. These id's are not used and converted to the natural ordering of nodes, as did for Abaqus / Nastran.

**Comment by kuateric** [comment]
I tried with a different mesh file. It worked fine. I could import and visualize in paraview without problem. 
The problem should be in fact what @tianyikillua mentioned. Our meshing tool does not necessary use an ordered list of Id's for nodes. We have always gab in the node list.  The reason for that is that we use oftly extruded meshes: i.e. We mesh a 2D model and extrude "manually" in the third direction to get a 3D-model. During this process, the user defines which Id-number he wants to use for the next layer of nodes. 

The .f3grid file i tested yet was modeled in 3D and meshed in ANSYS then converted to FLAC3D. Because of ANSYS, the nodes are necessarily ordered. Therefore I could convert the mesh properly. 
It would be nice if _flac3d.py can deal with those kind of meshes.

Thank you guys for your support.

**Comment by nschloe** [comment]
Aliright, reopening. So this is now a feature request for node ids in flac3d.

**Comment by keurfonluu** [comment]
I'll look into that today.

**Comment by keurfonluu** [comment]
Should be fixed now with PR #511.

![testmodel](https://user-images.githubusercontent.com/16566206/68791466-3b1fe700-05fe-11ea-8235-a5079813467d.png)

**Comment by kuateric** [comment]
Thank you @keurfonluu. I would have never thought the meshio community is so reactive. You solved all my issues in just few hours. Thank you very much.

**Comment by nschloe** [comment]
Alright, closing again. :smiley:

**Comment by kuateric** [comment]
hello @keurfonluu , 
i tried the newest version you pushed on github and already merged by @nschloe . I still get the crashing issue in paraview with the test file I uploaded here. Could you please try again if it works fine on your side? thank you.

**Comment by tianyikillua** [comment]
You will have to re-read the FLAC3D and then convert it to any format you want. The problem is not with ParaView but with how we read the mesh file.

**Comment by kuateric** [comment]
hello @tianyikillua , 
this is what i did. first i upgraded meshio:
![image](https://user-images.githubusercontent.com/22998049/68801868-2de61500-065d-11ea-95c4-3d1a895c6f75.png)
then i re-read the test-file and convert to vtu and vtk:
![image](https://user-images.githubusercontent.com/22998049/68801961-5110c480-065d-11ea-9045-bff714c1522c.png)
finally I tried to visualize those files in paraview. it crashed

**Comment by kuateric** [comment]
here are the files i converted: 
[testmodell5.zip](https://github.com/nschloe/meshio/files/3843398/testmodell5.zip)

**Comment by tianyikillua** [comment]
The updates have not been pushed to the official package index PyPI, where `pip` uses.

You can do `pip install -U git+https://github.com/nschloe/meshio` to download and install the latest development version.

**Comment by kuateric** [comment]
ahhh that is the problem. I tried pip install -U git+https://github.com/nschloe/meshio and I got an error. I will wait until @nschloe push it to the official package index. 
Thank you @tianyikillua

**Comment by keurfonluu** [comment]
You can also clone the GitHub repo and install using the local archive by executing from the root directory:

```
pip install -U .
```

**Comment by kuateric** [comment]
I tested my meshing file again with the newest version. It works very fine. The flac3d routine is now able to deal with non-ordered node ids. 
thank you @nschloe for uploading the newest version on PyPI. Thank you @keurfonluu for updating the routine. Thank you @tianyikillua for finding error ;) 
We can close this issue for good.
